server:
  port: 8080

spring:
  application:
    name: controlescolar

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/controlescolar
    username: controlescolar
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # usa validate/update en dev; en prod mejor validate + flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  
  thymeleaf:
        cache: false

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

